### PR TITLE
auto-populate command line with random node

### PR DESCRIPTION
**Pull request by bigreddmachine**
When you click the “Get Random Node” button, this will fill the node IP
into the copy pasta command lines for unix and windows.

### CODE REVIEW

**Comment by mjc87** [comment]
This will also fix the 0 vs 1 indexing issue I was describing before.

With JS arrays, indices start at 0 for the first item. ex: `var myarray = ['a', 'b', 'c'];` has indices 0, 1, and 2. But, the good news with your code, is `myarray.length = 3` still, so everything else should work.

**Comment by bigreddmachine** [comment]
This will also fix the 0 vs 1 indexing issue I was describing before.

With JS arrays, indices start at 0 for the first item. ex: `var myarray = ['a', 'b', 'c'];` has indices 0, 1, and 2. But, the good news with your code, is `myarray.length = 3` still, so everything else should work.

**Comment by Gingeropolous** [comment]
Thanks again!

**Comment by bigreddmachine** [comment]
np!

**Pull request merged**
